Feature/table pagination
loomi/react-leap pull request #2
Opened 2021-12-16 15:04 UTC by EdimarioJr

## Feature
 - Pagination component
 - Search Bar Component
 - useTable hook
 - Table component
 - unhandledRequest of MSW is now 'bypass' by default
---

**What I did:**

- Create a hook that handles the logic of pagination, search and sort in the table
- Create a table component
- Create a Pagination and Search component
- Deactivate the unhandledRequest warnings of msw
- Adapt the api handlers to use query parameters

**How to test:**

1. In your browser go to [stage](http://project.netlify.app/) or [localhost](http://localhost:3000/)
2. Check if the component/view looks just like the [mockup](https://xd.adobe.com/) in different screen sizes (width between 1024px and 1920px)
3. Test the things that you think are worth testing, even the ones that are not in this description

2021-12-16 21:17 UTC, Jorrmungandr requested changes

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +    const response: any = await axios.authorized({ mock: mockServer }).get(endpointWithParams);
Instead of creating this interpolation maybe something like this would do better:
```js
const response: any = await axios.authorized({ mock: mockServer }).get(endpoint, {
  params: {
    [nameSearch]: query,
    [nameLimit]: pageSize,
    [nameOffset]: offset,
    [nameOrder]: `${order?.column}:${order?.ord}`,
  },
});
```

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +    const response: any = await axios.authorized({ mock: mockServer }).get(endpointWithParams);
Instead of `any` maybe you could use `Response` type from `axios`.

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +    return response;
Newline here

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +    return response;
Newline here

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +    const response: number = await axios.authorized({ mock: mockServer }).get(countUrl);
Is the actual response a number? Isn't it like `response.data` that is the actual data from the request?

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +export async function getPaginatedData({
Use arrow function

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/api.ts
> +export async function getCount({ endpoint, mockServer }) {
Use arrow function

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/useTable.tsx
> +  const {
Newline here

2021-12-16 21:17 UTC, Jorrmungandr commented on src/components/Table/useTable.tsx
> +    error: errorPagData,
Instead of `loadingPagData` or `errorPagData` you could use `loadingPaginationData` so that the variable name is semantically easier to read it's a [clean code principle](https://medium.com/coding-skills/clean-code-101-meaningful-names-and-functions-bf450456d90c) (I think this article is pretty cool but you can also read it straight from uncle bob's)

2021-12-16 21:17 UTC, Jorrmungandr commented on src/modules/misc/pages/Landing.tsx
> +        <LC.Vertical pos="relative" zIndex="banner" center={true}>
Airbnb's react styleguide recommends [ommiting true properties](https://github.com/airbnb/javascript/tree/master/react#props)

2021-12-16 21:17 UTC, Jorrmungandr commented on src/test/server/handlers/expense.ts
> +      console.log(paramsObject);
Remove this

2021-12-16 21:17 UTC, Jorrmungandr commented on src/test/server/handlers/expense.ts
> +      console.log('passou');
Remove this

2021-12-16 21:17 UTC, Jorrmungandr commented on src/test/server/handlers/expense.ts
> +      console.log(error);
Remove this

2022-01-18 13:58 UTC, EdimarioJr commented on src/components/Table/Table.tsx
> +    );
what

2022-01-18 13:58 UTC, EdimarioJr commented on src/components/Table/Table.tsx
> +    );
what

2022-06-06 20:27 UTC, closed without merging